### ISSUE TITLE
iOS Carrier Demo

### ISSUE THREAD

**Issue by andersalm** [cyber-republic/react-native-elastos-carrier-demo#2]
Who: Developers and early adopters
What: A chat app built with React Native Framework (carrier npm)
Why: To show how it works, from both a developer and end user perspective

To do:
 - [x] front end
 - [x] user profile
 - [x] add friends
 - [x] see friends
 - [x] send message
 - [x] receive message
 - [x] sessions for sending and receiving files

**Comment by liyangwood** [comment]
done except the message history
that is not include in carrier.
